### ISSUE TITLE
Prevent reconnect on udp connections to localhost

### ISSUE THREAD

**Issue by breml** [logstash-plugins/logstash-output-syslog#19]
We don't expect udp connections to fail because they are stateless, but ...
udp connections may fail/raise an exception if used with localhost/127.0.0.1, if there is no one listening on the respective port.

To prevent a failing udp connection to localhost from halting the event
queue in logstash, we ignore exceptions if the connection is udp.

**Comment by suyograo** [comment]
Fixed in #20

**Comment by breml** [comment]
Close
