### ISSUE TITLE
Please add reconnect_interval option

### ISSUE THREAD

**Issue by gnhuy91** [logstash-plugins/logstash-output-syslog#24]
Just like the [tcp](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-tcp.html#plugins-outputs-tcp-reconnect_interval) plugin.

**Comment by breml** [comment]
@gnhuy91 This plugin already provides the config option `reconnect_interval` (see https://github.com/logstash-plugins/logstash-output-syslog/blob/master/lib/logstash/outputs/syslog.rb#L64 and https://github.com/logstash-plugins/logstash-output-syslog/blob/master/lib/logstash/outputs/syslog.rb#L191). Only the documentation on elastic.co (https://www.elastic.co/guide/en/logstash/current/plugins-outputs-syslog.html) is not updated yet. Therefore I close this issue as resolved.

If you don't agree, comment on this issue.
