### ISSUE TITLE
Double syslog header when using logstash-input-syslog and logstash-output-syslog

### ISSUE THREAD

**Issue by ddebast** [logstash-plugins/logstash-output-syslog#36]
Hello,

We are using logstash as a shipper to receive syslog messages and distribute them to multiple destinations.
When we receive message using the logstash-input-syslog plugin and forwarding them with logstash-output-syslog a double syslog header is present after the output which seems kind a logic.

My question is to have a parameter or option available which checks the input message and give the possibility to not add a second syslog header when a header was already present.

For all general issues, please provide the following details for fast resolution:

- Version: 2.4
- Operating System: Linux 6.8
- Config file:

`input {
  tcp {
    port => 5002
  }
}
output {
  syslog {
    facility => "daemon"
    host => "<IP>"
    port => 514
    severity => "alert"
    rfc => "rfc5424"
    appname => "dummy"
    protocol => ["tcp"]
  }
}`

**Comment by breml** [comment]
In this case, just use logstash-output-tcp.

See https://github.com/logstash-plugins/logstash-output-syslog/pull/35 as well.

**Comment by ddebast** [comment]
Thanks @breml for your reply!
I adapted the output plugin from syslog to tcp
Added host, port and codec "line"

The message after the TCP output looks like the following
`2017-04-13T12:15:04.587Z 10.109.1.187 <134>Apr 13 14:15:04 hostname 1,2017/04/13 14:15:04,...`

How can I remove the first part `2017-04-13T12:15:04.587Z 10.109.1.187 `?

**Comment by ddebast** [comment]
Hello,

In logstash 5.3 the same behavior is present.

I managed to get it working with the following config

output {
  tcp {
    host => ""
    port => 514
    codec => line {
      format => "%{message}"
    }
}

This info came from https://github.com/elastic/logstash/issues/5676 'sarvesh-du commented on Dec 13, 2016'

For me this issue is solved!
