### ISSUE TITLE
Dynamic configuration values.

### ISSUE THREAD

**Issue by incogniro** [logstash-plugins/logstash-output-syslog#7]
It is not possible to configure the plugin using interpolation with the values obtained from a log event.
Would you provide support for this as there are other plugins that support this feature. It is ideal to configure the plugin in a manner similar to:
```ruby
output {
	syslog {
		host		=> '10.11.12.1'
		port 		=> 12345
		protocol	=> 'tcp'
		facility 	=> %{SYSLOG_FACILITY}
		severity 	=> %{SYSLOG_SEVERITY}
		appname 	=> %{PROGRAM}
		sourcehost	=> %{LOGSOURCE}
		procid		=> %{PID}
		msgid		=> 'logstash'
	}
}
```
This would allow the forwarding of filtered events to a SYSLOG host with elements of the original event.

Thanks,

**Comment by ph** [comment]
Some initial work was done in this PR https://github.com/logstash-plugins/logstash-output-syslog/pull/4
