### ISSUE TITLE
Codec support

### ISSUE THREAD

**Issue by ManUnix** [logstash-plugins/logstash-output-syslog#9]
Hi,

it would be great if one could use the syslog output like this:
```ruby
syslog {
  [...]
  codec => my_codec
}
```

That would be helpful in order to transform the event to, for example, CEF (Common Event Format) and transmit it to a server via syslog.

The documentation (https://www.elastic.co/guide/en/logstash/current/plugins-outputs-syslog.html) states that "codec" is an available configuration option but for me it didn't work.
I guess "@codec.encode(event)" and a codec callback are missing.

**Comment by davidelang** [comment]
It's a bit more than just adding the codec call. I did a local version that did this, but another team overwrote it :-(

IIRC I had to modify the connection process as well as adding some additional libraries. I had it working using the json codec to output the message in that format, but I never did figure out what I needed to do to get it to output in the traditional message-only format.
